"use client";

import { cn } from "@/lib/utils";
import { 
  // Navigation & Layout
  Home,
  User,
  Users,
  Settings,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Link,
  Search,
  Filter,
  Grid,
  List,
  LayoutGrid,
  Maximize2,
  Minimize2,
  PanelLeft,
  PanelRight,
  Sidebar,
  Sheet,
  // Communication
  MessageCircle,
  MessageSquare,
  Send,
  Mail,
  Inbox,
  Bell,
  BellRing,
  BellOff,
  Phone,
  Video,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  // Content & Media
  Image,
  FileText,
  File,
  Folder,
  FolderOpen,
  Upload,
  Download,
  Cloud,
  CloudUpload,
  CloudDownload,
  Play,
  Pause,
  StopCircle,
  Volume2,
  VolumeX,
  // Actions
  Plus,
  Minus,
  Check,
  CheckCircle,
  CheckCircle2,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Trash2,
  Edit,
  Edit3,
  Copy,
  Clipboard,
  ClipboardCheck,
  RefreshCw,
  RotateCcw,
  RotateCw,
  MoreHorizontal,
  MoreVertical,
  GripVertical,
  // Status & Feedback
  Loader,
  Loader2,
  Sparkles,
  Zap,
  Flame,
  TrendingUp,
  TrendingDown,
  Activity,
  BarChart,
  BarChart2,
  PieChart,
  LineChart,
  // Security & Privacy
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Eye,
  EyeOff,
  Key,
  Fingerprint,
  // Crypto & Finance
  Wallet,
  Coins,
  DollarSign,
  CreditCard,
  Banknote,
  Receipt,
  ShoppingCart,
  Gift,
  Award,
  Trophy,
  Crown,
  Gem,
  Diamond,
  // Social
  Heart,
  HeartOff,
  ThumbsUp,
  ThumbsDown,
  Share2,
  Repeat,
  Repeat2,
  Flag,
  Bookmark,
  // Brand & Identity
  Globe,
  AtSign,
  Hash,
  Quote,
  Code,
  Terminal,
  Cpu,
  Database,
  Server,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  // Time & Calendar
  Clock,
  Calendar,
  CalendarDays,
  Timer,
  Hourglass,
  History,
  // Misc
  Moon,
  Sun,
  Star,
  MapPin,
  Navigation,
  Compass,
  Target,
  Crosshair,
  Scan,
  ScanLine,
  QrCode,
  BadgeCheck,
  Verified,
  Crown as CrownIcon,
  Rocket,
} from "lucide-react";

// Import Radix icons for variety
import {
  // Navigation
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  EnterIcon,
  ExitIcon,
  HamburgerMenuIcon,
  Cross1Icon,
  // Actions
  CheckIcon,
  CheckCircledIcon,
  CrossCircledIcon,
  ExclamationTriangleIcon,
  InfoCircledIcon,
  QuestionMarkCircledIcon,
  PlusIcon,
  MinusIcon,
  ReloadIcon,
  ResetIcon,
  UpdateIcon,
  TrashIcon,
  Pencil1Icon,
  Pencil2Icon,
  CopyIcon,
  ClipboardIcon,
  // Status
  RocketIcon,
  StarIcon,
  StarFilledIcon,
  HeartIcon,
  HeartFilledIcon,
  BookmarkIcon,
  BookmarkFilledIcon,
  BellIcon,
  // Communication
  ChatBubbleIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenIcon,
  PaperPlaneIcon,
  Share1Icon,
  Share2Icon,
  // Media
  ImageIcon,
  VideoIcon,
  SpeakerLoudIcon,
  SpeakerOffIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  TrackPreviousIcon,
  TrackNextIcon,
  // Layout
  DashboardIcon,
  MixIcon,
  LayoutIcon,
  GridIcon,
  ListBulletIcon,
  CardStackIcon,
  ViewGridIcon,
  ViewHorizontalIcon,
  ViewVerticalIcon,
  // Files
  FileIcon,
  FileTextIcon,
  ArchiveIcon,
  UploadIcon,
  DownloadIcon,
  // Arrows
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ThickArrowLeftIcon,
  ThickArrowRightIcon,
  ThickArrowUpIcon,
  ThickArrowDownIcon,
  // Symbols
  HomeIcon,
  PersonIcon,
  AvatarIcon,
  FaceIcon,
  IdCardIcon,
  GearIcon,
  MixerHorizontalIcon,
  MixerVerticalIcon,
  GlobeIcon,
  LockClosedIcon,
  LockOpen1Icon,
  LockOpen2Icon,
  EyeOpenIcon,
  EyeNoneIcon,
  EyeClosedIcon,
  // Finance
  TokensIcon,
  BackpackIcon,
  // Misc
  SunIcon,
  MoonIcon,
  MagnifyingGlassIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DotFilledIcon,
  DotIcon,
  ActivityLogIcon,
  TimerIcon,
  ClockIcon,
  CalendarIcon,
  ClipboardCopyIcon,
  CodeIcon,
  Component1Icon,
  ComponentPlaceholderIcon,
  ContainerIcon,
  CookieIcon,
  CrumpledPaperIcon,
  CubeIcon,
  CursorArrowIcon,
  DesktopIcon,
  DiscIcon,
  DropdownMenuIcon,
  EraserIcon,
  ExitFullScreenIcon,
  ExternalLinkIcon,
  FontStyleIcon,
  FontRomanIcon,
  FontItalicIcon,
  FontBoldIcon,
  FrameIcon,
  FramerLogoIcon,
  GitHubLogoIcon,
  TwitterLogoIcon,
  FigmaLogoIcon,
  VercelLogoIcon,
  StitchesLogoIcon,
} from "@radix-ui/react-icons";

export type IconSize = "xs" | "sm" | "md" | "lg" | "xl" | "2xl";
export type IconVariant = "default" | "filled" | "outlined" | "ghost";

const sizeMap: Record<IconSize, string> = {
  xs: "w-3 h-3",
  sm: "w-4 h-4",
  md: "w-5 h-5",
  lg: "w-6 h-6",
  xl: "w-8 h-8",
  "2xl": "w-10 h-10",
};

const strokeWidthMap: Record<IconSize, number> = {
  xs: 2.5,
  sm: 2,
  md: 1.5,
  lg: 1.5,
  xl: 1.25,
  "2xl": 1.25,
};

interface IconBaseProps {
  size?: IconSize;
  className?: string;
  variant?: IconVariant;
  animate?: boolean;
}

// Animated wrapper for icons
function IconWrapper({ 
  children, 
  className, 
  animate,
  size = "md"
}: { 
  children: React.ReactNode; 
  className?: string;
  animate?: boolean;
  size?: IconSize;
}) {
  return (
    <span 
      className={cn(
        "inline-flex items-center justify-center",
        sizeMap[size],
        animate && "animate-pulse",
        className
      )}
    >
      {children}
    </span>
  );
}

// Premium Icon Component with Lucide
export function PremiumIcon({ 
  icon: Icon, 
  size = "md", 
  className,
  variant = "default",
  animate,
}: IconBaseProps & { icon: React.ElementType }) {
  const strokeWidth = strokeWidthMap[size];
  
  const variantClasses = {
    default: "",
    filled: "fill-current",
    outlined: "fill-none",
    ghost: "opacity-60",
  };

  return (
    <IconWrapper className={className} animate={animate} size={size}>
      <Icon 
        className={cn(
          sizeMap[size],
          variantClasses[variant],
          "transition-all duration-200"
        )}
        strokeWidth={strokeWidth}
      />
    </IconWrapper>
  );
}

// Re-export all Lucide icons with premium styling
export {
  // Navigation
  Home,
  User,
  Users,
  Settings,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Link,
  Search,
  Filter,
  Grid,
  List,
  LayoutGrid,
  Maximize2,
  Minimize2,
  PanelLeft,
  PanelRight,
  Sidebar,
  Sheet,
  // Communication
  MessageCircle,
  MessageSquare,
  Send,
  Mail,
  Inbox,
  Bell,
  BellRing,
  BellOff,
  Phone,
  Video,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  // Content
  Image,
  FileText,
  File,
  Folder,
  FolderOpen,
  Upload,
  Download,
  Cloud,
  CloudUpload,
  CloudDownload,
  Play,
  Pause,
  StopCircle,
  Volume2,
  VolumeX,
  // Actions
  Plus,
  Minus,
  Check,
  CheckCircle,
  CheckCircle2,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Trash2,
  Edit,
  Edit3,
  Copy,
  Clipboard,
  ClipboardCheck,
  RefreshCw,
  RotateCcw,
  RotateCw,
  MoreHorizontal,
  MoreVertical,
  GripVertical,
  // Status
  Loader,
  Loader2,
  Sparkles,
  Zap,
  Flame,
  TrendingUp,
  TrendingDown,
  Activity,
  BarChart,
  BarChart2,
  PieChart,
  LineChart,
  // Security
  Lock,
  Unlock,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Eye,
  EyeOff,
  Key,
  Fingerprint,
  // Crypto
  Wallet,
  Coins,
  DollarSign,
  CreditCard,
  Banknote,
  Receipt,
  ShoppingCart,
  Gift,
  Award,
  Trophy,
  Crown,
  Gem,
  Diamond,
  // Social
  Heart,
  HeartOff,
  ThumbsUp,
  ThumbsDown,
  Share2,
  Repeat,
  Repeat2,
  Flag,
  Bookmark,
  // Brand
  Globe,
  AtSign,
  Hash,
  Quote,
  Code,
  Terminal,
  Cpu,
  Database,
  Server,
  Wifi,
  WifiOff,
  Bluetooth,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  // Time
  Clock,
  Calendar,
  CalendarDays,
  Timer,
  Hourglass,
  History,
  // Misc
  Moon,
  Sun,
  Star,
  MapPin,
  Navigation,
  Compass,
  Target,
  Crosshair,
  Scan,
  ScanLine,
  QrCode,
  BadgeCheck,
  Verified,
  CrownIcon,
  Rocket,
};

// Re-export Radix icons (all with Icon suffix)
export {
  // Navigation
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  EnterIcon,
  ExitIcon,
  HamburgerMenuIcon,
  Cross1Icon,
  // Actions
  CheckIcon,
  CheckCircledIcon,
  CrossCircledIcon,
  ExclamationTriangleIcon,
  InfoCircledIcon,
  QuestionMarkCircledIcon,
  PlusIcon,
  MinusIcon,
  ReloadIcon,
  ResetIcon,
  UpdateIcon,
  TrashIcon,
  Pencil1Icon,
  Pencil2Icon,
  CopyIcon,
  ClipboardIcon,
  // Status
  RocketIcon,
  StarIcon,
  StarFilledIcon,
  HeartIcon,
  HeartFilledIcon,
  BookmarkIcon,
  BookmarkFilledIcon,
  BellIcon,
  // Communication
  ChatBubbleIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenIcon,
  PaperPlaneIcon,
  Share1Icon,
  Share2Icon,
  // Media
  ImageIcon,
  VideoIcon,
  SpeakerLoudIcon,
  SpeakerOffIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  TrackPreviousIcon,
  TrackNextIcon,
  // Layout
  DashboardIcon,
  MixIcon,
  LayoutIcon,
  GridIcon,
  ListBulletIcon,
  CardStackIcon,
  ViewGridIcon,
  ViewHorizontalIcon,
  ViewVerticalIcon,
  // Files
  FileIcon,
  FileTextIcon,
  ArchiveIcon,
  UploadIcon,
  DownloadIcon,
  // Arrows
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  ThickArrowLeftIcon,
  ThickArrowRightIcon,
  ThickArrowUpIcon,
  ThickArrowDownIcon,
  // Symbols
  HomeIcon,
  PersonIcon,
  AvatarIcon,
  FaceIcon,
  IdCardIcon,
  GearIcon,
  MixerHorizontalIcon,
  MixerVerticalIcon,
  GlobeIcon,
  LockClosedIcon,
  LockOpen1Icon,
  LockOpen2Icon,
  EyeOpenIcon,
  EyeNoneIcon,
  EyeClosedIcon,
  // Finance
  TokensIcon,
  BackpackIcon,
  // Misc
  SunIcon,
  MoonIcon,
  MagnifyingGlassIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DotFilledIcon,
  DotIcon,
  ActivityLogIcon,
  TimerIcon,
  ClockIcon,
  CalendarIcon,
  ClipboardCopyIcon,
  CodeIcon,
  Component1Icon,
  ComponentPlaceholderIcon,
  ContainerIcon,
  CookieIcon,
  CrumpledPaperIcon,
  CubeIcon,
  CursorArrowIcon,
  DesktopIcon,
  DiscIcon,
  DropdownMenuIcon,
  EraserIcon,
  ExitFullScreenIcon,
  ExternalLinkIcon,
  FontStyleIcon,
  FontRomanIcon,
  FontItalicIcon,
  FontBoldIcon,
  FrameIcon,
  FramerLogoIcon,
  GitHubLogoIcon,
  TwitterLogoIcon,
  FigmaLogoIcon,
  VercelLogoIcon,
  StitchesLogoIcon,
};
